name: env-action
description: Github Action to create .env using secrets.
inputs:
  PATH:
    description: "Path to the app directory."
    required: true
  SECRETS:
    description: "Pass secrets to be used in action."
    required: true
runs:
  using: "node16"
  main: "dist/index.js"
